#!/bin/bash

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

alias c='clear'
alias h='history'
alias l='ls -F -G'
alias ll='ls -ltr -F -G'
alias la='ls -a -F -G'
alias em='emacs -nw'
alias yuicompressor='java -jar /usr/local/yuicompressor-2.4.7/yuicompressor/yuicompressor.jar'
alias df='df -h'