#!/bin/bash

case "$2" in
    merge|squash|commit)
        echo exiting
        exit 0;;
esac

BRANCH=$(git rev-parse --abbrev-ref HEAD)

case "$BRANCH" in
    HEAD|master)
        exit 0;;
esac

TMPFILE=$(mktemp /tmp/ff-commit.XXXXXXX)
ISSUE=$(echo "$BRANCH" | cut -d _ -f 1)

echo -n "[#"$ISSUE"] " > "$TMPFILE"
cat "$1" >> "$TMPFILE"

mv "$TMPFILE" "$1"
